/** Generated by lib/icons/encode.mjs */
export type MapIconType =
  | "icon-animal"
  | "icon-bed"
  | "icon-beer"
  | "icon-book-shop"
  | "icon-bow"
  | "icon-camp"
  | "icon-castle"
  | "icon-cave"
  | "icon-combat"
  | "icon-dragon"
  | "icon-flag"
  | "icon-hall"
  | "icon-house"
  | "icon-landmark"
  | "icon-magic-shop"
  | "icon-magic"
  | "icon-marker-red"
  | "icon-marker"
  | "icon-religion"
  | "icon-shield"
  | "icon-shop"
  | "icon-signpost"
  | "icon-skull"
  | "icon-smith"
  | "icon-spellbook"
  | "icon-trail"
  | "icon-treasure"
  | "icon-tree";

/** Generated by lib/icons/encode.mjs */
export const MapIcons: MapIconType[] = [
  "icon-animal",
  "icon-bed",
  "icon-beer",
  "icon-book-shop",
  "icon-bow",
  "icon-camp",
  "icon-castle",
  "icon-cave",
  "icon-combat",
  "icon-dragon",
  "icon-flag",
  "icon-hall",
  "icon-house",
  "icon-landmark",
  "icon-magic-shop",
  "icon-magic",
  "icon-marker-red",
  "icon-marker",
  "icon-religion",
  "icon-shield",
  "icon-shop",
  "icon-signpost",
  "icon-skull",
  "icon-smith",
  "icon-spellbook",
  "icon-trail",
  "icon-treasure",
  "icon-tree",
];
