import { IconName } from "@fortawesome/fontawesome-common-types";

export const Icons: IconName[] = [
  "map-pin",
  "map-signs",
  "map-marker-alt",
  "map-marker",
  "shoe-prints",
  "route",
  "paw",
  "tree",
  "beer",
  "chess-rook",
  "fist-raised",
  "campground",
  "shield-alt",
  "skull-crossbones",
  "skull",
  "eye",
  "dungeon",
  "archway",
  "landmark",
  "hat-wizard",
  "dice-d20",
  "dragon",
  "scroll",
  "fire",
  "home",
  "store",
  "store-alt",
  "cash-register",
  "road",
  "bed",
];
